import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve('public');
function file(rel){return path.join(root,rel,'index.html')}
function read(rel){return fs.readFileSync(file(rel),'utf8')}
function write(rel,html){fs.writeFileSync(file(rel),html)}
function main(html,body){return html.replace(/<main class="main-content">[\s\S]*?<\/main>/i,`<main class="main-content">${body}</main>`)}
function title(html,text){return html.replace(/<title>[\s\S]*?<\/title>/i,`<title>${text} | East Tennessee Chihuahuas</title>`)}

const deposit=`
<section class="page-header"><div><span class="page-eyebrow">CUSTOMER DOCUMENT PREVIEW</span><h1>Deposit &amp; Reservation Agreement</h1><p>This page explains the standard reservation terms families can review before sending a deposit. The puppy-specific signed agreement controls the actual transaction.</p></div></section>
<section class="document-sheet section-space"><div class="document-actions"><button class="button ghost" type="button" onclick="window.print()">PRINT / SAVE PDF</button><a class="button primary" href="/application/">START APPLICATION</a></div>
<div class="document-title"><span>EAST TENNESSEE CHIHUAHUAS</span><h2>Deposit &amp; Reservation Agreement</h2><p>Johnson City, Tennessee</p></div>
<section><h3>1. Purpose of the Deposit</h3><p>A reservation deposit is accepted only after the buyer has been approved and a specific puppy has been identified for placement. The deposit removes that puppy from public availability while the parties prepare for completion of the sale.</p></section>
<section><h3>2. Deposit Amount</h3><p>Reservation deposits generally range from <strong>$250 to $500</strong>. The exact amount is stated in the puppy-specific agreement and is credited toward the final purchase price.</p></section>
<section><h3>3. Non-Refundable Buyer Cancellation</h3><p>Once a specific puppy has been reserved and removed from availability, the deposit is generally non-refundable if the buyer changes their mind, fails to complete payment, becomes unavailable for transfer, or otherwise elects not to complete the purchase for reasons unrelated to the puppy's health or our ability to complete the placement.</p></section>
<section><h3>4. If We Cannot Complete the Placement</h3><p>If East Tennessee Chihuahuas determines before go-home that the puppy should not be placed because of a health, developmental, or welfare concern, the buyer will be offered the options stated in the signed agreement, which may include transferring the reservation to another appropriate puppy or receiving a refund of reservation funds.</p></section>
<section><h3>5. Remaining Balance</h3><p>The remaining purchase balance is due according to the Bill of Sale or any separately approved written payment arrangement. A puppy will not transfer until required payment and documents are complete.</p></section>
<section><h3>6. Puppy Readiness</h3><p>A reservation does not guarantee a fixed go-home date. Eight weeks is our minimum placement age, and an individual puppy may stay longer when development, size, appetite, health, or transition readiness calls for additional time.</p></section>
<section><h3>7. Registration and Breeding Rights</h3><p>Registry and breeding-rights terms are puppy-specific. Companion placement does not automatically include breeding rights. Any breeding authorization must be stated in writing.</p></section>
<section><h3>8. Transportation</h3><p>Pickup, meet-up, ground transport, and any Pup-Lift arrangements are handled separately from the reservation deposit unless the written agreement states otherwise. Transportation is not considered final until confirmed in writing.</p></section>
<section><h3>9. Buyer Information</h3><div class="signature-grid"><p>Buyer: ______________________________</p><p>Puppy: ______________________________</p><p>Deposit: $___________________________</p><p>Date: _______________________________</p></div></section>
<section><h3>10. Acknowledgment</h3><p>By signing the puppy-specific agreement, the buyer confirms that the reservation terms, refund terms, balance due, and expected transfer plan have been reviewed before payment is submitted.</p></section>
<div class="signature-grid final-sign"><p>Buyer Signature: ______________________________</p><p>Date: __________________</p><p>Breeder Signature: ____________________________</p><p>Date: __________________</p></div></section>`;
let h=read('deposit-agreement');h=main(h,deposit);h=title(h,'Deposit & Reservation Agreement');write('deposit-agreement',h);

const bill=`
<section class="page-header"><div><span class="page-eyebrow">CUSTOMER DOCUMENT PREVIEW</span><h1>Puppy Bill of Sale</h1><p>Families can review our standard sale terms before placement. Final puppy-specific information, price, registration status, health findings, and transfer details are completed on the signed agreement.</p></div></section>
<section class="document-sheet section-space"><div class="document-actions"><button class="button ghost" type="button" onclick="window.print()">PRINT / SAVE PDF</button><a class="button primary" href="/health-guarantee/">HEALTH GUARANTEE</a></div>
<div class="document-title"><span>EAST TENNESSEE CHIHUAHUAS</span><h2>Puppy Sales Agreement &amp; Bill of Sale</h2><p>Johnson City, Tennessee</p></div>
<section><h3>1. Buyer and Puppy</h3><div class="signature-grid"><p>Buyer: ______________________________</p><p>Phone/Email: ________________________</p><p>Puppy Name/ID: _____________________</p><p>Date of Birth: ______________________</p><p>Sex: _______________________________</p><p>Color/Coat: _________________________</p><p>Registry: ___________________________</p><p>Sire / Dam: _________________________</p></div></section>
<section><h3>2. Purchase Price and Payments</h3><p>Total purchase price: $________________. Reservation deposit paid: $________________. Remaining balance: $________________. Any approved financing or structured payment arrangement must be documented separately in writing.</p></section>
<section><h3>3. Transfer of Ownership</h3><p>Ownership transfers only after required payment has cleared, this Bill of Sale and applicable documents are completed, and the puppy is physically released to the buyer or authorized transporter.</p></section>
<section><h3>4. Health Records and Veterinary Examination</h3><p>The buyer receives the puppy-specific vaccination, deworming, and available veterinary records that apply to the puppy. The buyer agrees to have the puppy examined by a licensed veterinarian within the timeframe required by the Health Guarantee, currently 72 hours after go-home.</p></section>
<section><h3>5. Health Guarantee</h3><p>The written Health Guarantee is incorporated into the placement. It explains covered congenital or genetic conditions, exclusions, veterinary documentation requirements, and the process for making a claim.</p></section>
<section><h3>6. Size and Development</h3><p>Any projected adult weight or size is an estimate only. East Tennessee Chihuahuas does not guarantee an exact adult weight, final coat, color intensity, ear set, or mature appearance.</p></section>
<section><h3>7. Registration and Breeding</h3><p>The puppy's registration terms are stated on the final agreement. Breeding rights are not included unless specifically approved in writing. Limited or companion placement restrictions, when applicable, remain part of the sale terms.</p></section>
<section><h3>8. Care Responsibilities</h3><p>The buyer agrees to provide appropriate nutrition, routine veterinary care, vaccinations as recommended by their veterinarian, safe housing, supervision, socialization, and protection from preventable injury. Additional requirements for very small puppies are described in the Buyer Care Agreement and Small Puppy Safety Policy.</p></section>
<section><h3>9. Lifetime Return</h3><p>If the buyer can no longer keep the dog, East Tennessee Chihuahuas must be contacted before the dog is sold, surrendered, gifted, transferred, or independently rehomed, consistent with our Lifetime Return &amp; Rehoming Policy.</p></section>
<section><h3>10. Transportation</h3><p>Pickup or transportation arrangements are confirmed separately. Any third-party ground transport, including Pup-Lift when selected, is subject to the written transportation terms and scheduling availability.</p></section>
<section><h3>11. Entire Agreement</h3><p>The signed puppy-specific Bill of Sale, Health Guarantee, applicable addenda, and referenced policies make up the placement agreement. Any special condition must be written into the final documents.</p></section>
<div class="signature-grid final-sign"><p>Buyer Signature: ______________________________</p><p>Date: __________________</p><p>Breeder Signature: ____________________________</p><p>Date: __________________</p></div></section>`;
h=read('bill-of-sale');h=main(h,bill);h=title(h,'Puppy Bill of Sale');write('bill-of-sale',h);

const hub=`
<section class="page-header"><div><span class="page-eyebrow">POLICIES &amp; CONTRACTS</span><h1>Read the important terms before you reserve.</h1><p>We keep the individual documents separate so families can review exactly what applies without digging through one enormous legal page.</p></div></section>
<section class="document-hub section-space">
<a class="panel doc-card" href="/deposit-agreement/"><span>RESERVATION</span><h2>Deposit Agreement</h2><p>Reservation amounts, cancellation terms, balance due, readiness, and transportation.</p></a>
<a class="panel doc-card" href="/bill-of-sale/"><span>SALE</span><h2>Bill of Sale</h2><p>Purchase price, transfer, registration, care obligations, health terms, and signatures.</p></a>
<a class="panel doc-card" href="/health-guarantee/"><span>HEALTH</span><h2>1-Year Health Guarantee</h2><p>Coverage, exclusions, veterinary examination requirements, and claims.</p></a>
<a class="panel doc-card" href="/lifetime-return/"><span>LIFETIME</span><h2>Return &amp; Rehoming Policy</h2><p>What to do if a family can no longer keep a dog we placed.</p></a>
<a class="panel doc-card" href="/buyer-care-agreement/"><span>CARE</span><h2>Buyer Care Agreement</h2><p>Nutrition, supervision, veterinary care, safety, and ongoing responsibilities.</p></a>
<a class="panel doc-card" href="/small-puppy-policy/"><span>SMALL PUPPY</span><h2>Small Puppy Safety</h2><p>Additional feeding, supervision, temperature, and hypoglycemia precautions.</p></a>
<a class="panel doc-card" href="/transportation-policy/"><span>TRANSFER</span><h2>Transportation Policy</h2><p>Pickup, meet-up, third-party transport, and Pup-Lift arrangements.</p></a>
<a class="panel doc-card" href="/financing-addendum/"><span>PAYMENTS</span><h2>Financing Addendum</h2><p>Separate written terms for any approved structured payment arrangement.</p></a>
<a class="panel doc-card" href="/breeding-rights-policy/"><span>REGISTRATION</span><h2>Breeding Rights Policy</h2><p>Companion placement, approval requirements, and written breeding authorization.</p></a>
<a class="panel doc-card" href="/terms/"><span>WEBSITE</span><h2>Terms</h2><p>General website and program terms.</p></a>
<a class="panel doc-card" href="/privacy/"><span>PRIVACY</span><h2>Privacy</h2><p>How application and contact information is handled.</p></a>
</section>`;
h=read('policies');h=main(h,hub);h=title(h,'Policies & Contracts');write('policies',h);

const css=`\n.document-sheet{max-width:980px;margin-left:auto;margin-right:auto;background:#fff;border:1px solid #d8e4ed;border-radius:16px;padding:42px;box-shadow:0 16px 40px rgba(9,38,65,.06)}.document-actions{display:flex;gap:10px;justify-content:flex-end;margin-bottom:26px}.document-title{text-align:center;border-bottom:2px solid #0b2946;padding-bottom:24px;margin-bottom:26px}.document-title span{font-size:.75rem;font-weight:900;letter-spacing:.12em;color:#0670ad}.document-title h2{font-size:2rem;margin:.4rem 0}.document-sheet section{border-bottom:1px solid #e1e9ef;padding:8px 0 18px;margin-bottom:14px}.document-sheet h3{margin-bottom:.45rem}.document-sheet p{line-height:1.65;color:#40586d}.signature-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px 28px}.final-sign{margin-top:30px;padding-top:24px;border-top:2px solid #0b2946}.document-hub{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.doc-card{text-decoration:none;color:inherit;transition:transform .15s ease,box-shadow .15s ease}.doc-card:hover{transform:translateY(-2px);box-shadow:0 12px 30px rgba(9,38,65,.08)}.doc-card span{font-size:.72rem;letter-spacing:.12em;font-weight:900;color:#0670ad}.doc-card h2{margin:.45rem 0}.doc-card p{color:#61768a}@media(max-width:900px){.document-hub{grid-template-columns:1fr 1fr}}@media(max-width:650px){.document-sheet{padding:24px}.signature-grid,.document-hub{grid-template-columns:1fr}.document-actions{justify-content:stretch;flex-direction:column}}@media print{.sidebar,.topbar,.footer,.nav-scrim,.document-actions{display:none!important}.workspace{margin:0!important}.main-content{padding:0!important}.document-sheet{box-shadow:none;border:0;padding:0;max-width:none}}\n`;
fs.appendFileSync(path.join(root,'assets','styles.css'),css);
console.log('Contract consistency pass applied.');
